import { create } from 'zustand';
import { UserAdvancedProfile } from '@/types/user.type';

export interface UserAdvancedProfileState {
  [key: string]: any,
  additionalNotes: string,
  familiarIndustry: string[],
  film: string,
  hobbies: string[],
  oneweekTravel: string,
  permanentTravel: string,
  professional: string[],
  speciality: any,
  technicalSkills: string[],
  advancedProfile: UserAdvancedProfile,
  getAdditionalNotes: () => string,
  getFilm: () => string,
  getOneweekTravel: () => string,
  getPermanentTravel: () => string,
  getFamiliarIndustry: () => string[],
  getHobbies: () => string[],
  getProfessional: () => string[],
  getSpeciality: () => any,
  getTechnicalSkills: () => string[],
  getAdvancedProfile: () => UserAdvancedProfile,
  setAdditionalNotes: (additionalNotes: string) => void,
  setFilm: (film: string) => void,
  setOneweekTravel: (oneweekTravel: string) => void,
  setPermanentTravel: (permanentTravel: string) => void,
  setFamiliarIndustry: (familiarIndustry: string[]) => void,
  setHobbies: (hobbies: string[]) => void,
  setProfessional: (professional: string[]) => void,
  setSpeciality: (speciality: any) => void,
  setTechnicalSkills: (technicalSkills: string[]) => void,
  setAdvancedProfile: (advancedProfile: UserAdvancedProfile) => void,
}

const useAdvancedProfileStore = create<UserAdvancedProfileState>((set, get) => ({
  firstName: "",
  middleName: "",
  lastName: "",
  mobileNumber: "",
  emailAddress: "",
  linkedinProfile: "",
  twitterProfile: "",
  country: "",
  region: "",
  residenceCity: "",
  referrer: "",
  mentorExperience: "",
  membershipInterest: [],
  meetTime: [],
  basicProfile: {},

  additionalNotes: "",
  familiarIndustry: [],
  film: "",
  hobbies: [],
  oneweekTravel: "",
  permanentTravel: "",
  professional: [],
  speciality: {},
  technicalSkills: [],
  advancedProfile: {},

  getAdditionalNotes: () => get().additionalNotes,
  getFilm: () => get().film,
  getOneweekTravel: () => get().oneweekTravel,
  getPermanentTravel: () => get().permanentTravel,
  getFamiliarIndustry: () => get().familiarIndustry,
  getHobbies: () => get().hobbies,
  getProfessional: () => get().professional,
  getSpeciality: () => get().speciality,
  getTechnicalSkills: () => get().technicalSkills,
  getAdvancedProfile: () => get().advancedProfile,
  setAdditionalNotes: (additionalNotes: string) => set((state) => ({ additionalNotes: additionalNotes })),
  setFilm: (film: string) => set((state) => ({ film: film })),
  setOneweekTravel: (oneweekTravel: string) => set((state) => ({ oneweekTravel: oneweekTravel })),
  setPermanentTravel: (permanentTravel: string) => set((state) => ({ permanentTravel: permanentTravel })),
  setFamiliarIndustry: (familiarIndustry: string[]) => set((state) => ({ familiarIndustry: familiarIndustry })),
  setHobbies: (hobbies: string[]) => set((state) => ({ hobbies: hobbies })),
  setProfessional: (professional: string[]) => set((state) => ({ professional: professional })),
  setSpeciality: (speciality: any) => set((state) => ({ speciality: speciality })),
  setTechnicalSkills: (technicalSkills: string[]) => set((state) => ({ technicalSkills: technicalSkills })),
  setAdvancedProfile: (advancedProfileData: UserAdvancedProfile) => set((state) => ({ advancedProfile: advancedProfileData }))
}));

export default useAdvancedProfileStore;